### ISSUE TITLE
PHP 7.0 support

### ISSUE THREAD

**Issue by sarukuku** [bestwebsoft/google-captcha-recaptcha-wordpress-plugin#7]
I switched to PHP 7.0 on my dev machine and I'm getting "headers already sent" errors on the environments where I have the captcha installed. Clarifying image below. With PHP 5.6.10 I have no problems what so ever.

The constructor should probably be updated as well.

<img width="1440" alt="screenshot 2015-12-29 11 14 58" src="https://cloud.githubusercontent.com/assets/1204559/12032130/6d1e3c30-ae1d-11e5-85b7-cc04939713ab.png">

**Comment by bestwebsoft** [comment]
Hi,

Thank you for your message. We'll explore this problem and fix it in the nearest plugin update.

Sincerely,
BestWebSoft Support Team

**Comment by sarukuku** [comment]
👍🏻
